version: '3.8'

services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/mi-grupo-ja-frontend:latest
    # Alternativa: construir localmente
    # build:
    #   context: .
    #   dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatpdf?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret
      - BACKEND_URL=http://backend:5000
      - NODE_ENV=production
    depends_on:
      - backend
      - db
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: ${DOCKERHUB_USERNAME}/mi-grupo-ja-backend:latest
    # Alternativa: construir localmente
    # build:
    #   context: .
    #   dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - PORT=5000
    volumes:
      - pdf_data:/app/pdf_files
      - chroma_data:/app/chroma_db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatpdf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  pdf_data:
  chroma_data:

networks:
  app-network:
    driver: bridge